/*
 * This source file was generated by the Gradle 'init' task
 */
package transfast;

import transfast.RobotHelper;
import transfast.KeyboardListener;

public class App {
    public String getGreeting() {
        return "System is running...";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        KeyboardListener.main(args);
    }
}
